### ISSUE TITLE
ヘッダーのカンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/bookshelf#103]
Studyplusや読書メーカーを参考にしながらヘッダーのカンプを作成する(紙に書いても良い)

カンプでき次第Sassのコーディングに移行するため、優先度高めです。

完成したらリンク又は写真をissueにコメントしてください。

**Comment by takashi0602** [comment]
studyplusと読書メーターを参考にして考えました。 **「これ嫌だ！」** とか **「もっとこうした方がいい！」** とか何でもいいのでコメント下さい。

![s__203423746](https://user-images.githubusercontent.com/30039352/32089702-77ef99a2-bb26-11e7-9be1-545da5255ec8.jpg)

**Comment by tyokinuhata** [comment]
新規登録 -> サインアップ
ログイン -> サインイン
ログアウト -> サインアウト
に変更お願いします。

キャッチフレーズはトップ画面に表示するため削除で。
Bookshelfとは, 利用方法, サインアウト云々はサインイン後にプルダウンメニューとして表現。

じぶんの本棚, みんなの本棚を今のマイページの隣に表示お願いします。

**Comment by takashi0602** [comment]
![s__203456514](https://user-images.githubusercontent.com/30039352/32090933-d4e00b5a-bb2c-11e7-8500-89f6d85d0117.jpg)

**Comment by tyokinuhata** [comment]
ロゴとBookshelfの文字をマイページの横に入れちゃって

**Comment by takashi0602** [comment]
修正しました。

![s__203513859](https://user-images.githubusercontent.com/30039352/32093085-081d0ffa-bb36-11e7-841f-0811e6fb8b76.jpg)
