### ISSUE TITLE
トップ画面のカンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/bookshelf#104]
Studyplusや読書メーカーを参考にしながらトップ画面のカンプを作成する(紙に書いても良い)

カンプでき次第Sassのコーディングに移行するため、優先度高めです。

完成したらリンク又は写真をissueにコメントしてください。

**Comment by takashi0602** [comment]
- みんなの本棚は一部だけ見せ、「もっと見る」ボタンからみんなの本棚に遷移する。
- 「詳細」ボタンはいらないと思い、タイトルだけにした。

![s__204185603](https://user-images.githubusercontent.com/30039352/32205254-985dc692-be31-11e7-9cd8-8a8693eca12b.jpg)

**Comment by takashi0602** [comment]
キャッチフレーズ
「知識の海を駆け抜けろ」
