### ISSUE TITLE
じぶんの本棚 カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/bookshelf#105]
Studyplusや読書メーカーを参考にしながらじぶんの本棚のカンプを作成する(紙に書いても良い)

カンプでき次第Sassのコーディングに移行するため、優先度高めです。

完成したらリンク又は写真をissueにコメントしてください。

**Comment by takashi0602** [comment]
- １画面に本の追加と一覧を表示すると見にくいと思ったので分けました。
- 「削除」ボタンは更新処理ページ内にあった方がいいと思い、「削除」ボタンはありません。

![s__203726850](https://user-images.githubusercontent.com/30039352/32134099-9090a41a-bc20-11e7-9f57-b51b632dcf97.jpg)
![s__203710466](https://user-images.githubusercontent.com/30039352/32134101-96cb853e-bc20-11e7-8429-a008e28d29a9.jpg)

**Comment by tyokinuhata** [comment]
じぶんの本棚に更新ボタンは置かず、詳細ボタンを設置

詳細ページから更新処理、削除処理をできるUIに変更お願いします。

また、本の追加ページ、更新ページ、削除ページ、詳細ページはそれぞれissueを立ててカンプ作成お願いします。

**Comment by takashi0602** [comment]
![s__203710467](https://user-images.githubusercontent.com/30039352/32134540-0bde693c-bc2a-11e7-97cc-6db90e4f0310.jpg)
