### ISSUE TITLE
みんなの本棚 詳細 カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/bookshelf#107]
Studyplusや読書メーカーを参考にしながらみんなの本棚の詳細ページのカンプを作成する(紙に書いても良い)

カンプでき次第Sassのコーディングに移行するため、優先度高めです。

完成したらリンク又は写真をissueにコメントしてください。

**Comment by takashi0602** [comment]
![s__203530243](https://user-images.githubusercontent.com/30039352/32094690-a7e40584-bb3b-11e7-9f38-a5541e6a8ae6.jpg)
