### ISSUE TITLE
フッター カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/bookshelf#121]
現在はフッターが存在しませんが, フッターを新たに考案お願いします

**Comment by takashi0602** [comment]
![s__204185602](https://user-images.githubusercontent.com/30039352/32204449-9b37b058-be2c-11e7-8d0d-f6858c3ffc19.jpg)

**Comment by tyokinuhata** [comment]
Copyrightと©は同じ意味なので©は消す方向で。
あとはBookshelfをASSに変更かな

**Comment by takashi0602** [comment]
修正しました。

![s__204251140](https://user-images.githubusercontent.com/30039352/32210894-6158a23a-be53-11e7-9306-cca084d61263.jpg)
