### ISSUE TITLE
本のジャンル洗い出し

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/bookshelf#124]
技術書, コミック, 学参など, 本のジャンルの洗い出しをお願いします.

書籍登録時に本のジャンルも登録する機能を実装する際に参考にします.

ジャンルはできるだけ基本的なもののみに絞ってください.

マニアックなジャンルに関しては「ユーザ定義ジャンル」として, ユーザが独自にジャンルを作成する形で実装する予定です.

**Comment by takashi0602** [comment]
書くと時間がかかるため、参考にしたサイトのurlと画像を貼っときます。
http://www.j-n.co.jp/books/genrelist.html

<img width="786" alt="2017-10-28 22 02 17" src="https://user-images.githubusercontent.com/30039352/32134621-c8e1dedc-bc2b-11e7-8e4f-4c1e09fc9fc2.png">
<img width="784" alt="2017-10-28 22 02 34" src="https://user-images.githubusercontent.com/30039352/32134622-cbe9059c-bc2b-11e7-8a52-754528e393e5.png">

**Comment by tyokinuhata** [comment]
- ビジネス
- 文芸
- 教養
- ガイド
- 趣味
- 実用
- 自己啓発
- コミックス

その他はユーザー定義ジャンルで対応
