### ISSUE TITLE
詳細ページ カンプ作成

### ISSUE THREAD

**Issue by takashi0602** [tyokinuhata/bookshelf#130]

**Comment by takashi0602** [comment]
![s__203923459](https://user-images.githubusercontent.com/30039352/32136678-e6d2b684-bc4c-11e7-9ad2-a0242283d9bd.jpg)

**Comment by tyokinuhata** [comment]
更新 -> 編集 に変更

**Comment by takashi0602** [comment]
![s__203923460](https://user-images.githubusercontent.com/30039352/32136724-c98af928-bc4d-11e7-947d-b85b30b1f42f.jpg)
