### ISSUE TITLE
じぶんの本棚 詳細ページ カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/bookshelf#140]
じぶんの本棚の詳細ページのカンプについては完成済みなのでじぶんの本棚の詳細ページ(差分のみ)をお願いします。

**Comment by tyokinuhata** [comment]
じぶんの本棚の詳細ページのカンプについては完成済みなのでじぶんの本棚の詳細ページ(差分のみ)をお願いします。

**Comment by takashi0602** [comment]
![s__204169218](https://user-images.githubusercontent.com/30039352/32202249-b481bea4-be1e-11e7-8bd8-ed49f7f4d626.jpg)
