### ISSUE TITLE
トップページのマークアップ

### ISSUE THREAD

**Issue by takashi0602** [tyokinuhata/bookshelf#44]
- [x] トップページを作成する。
- [ ] ログイン画面に遷移する。
- [ ] みんなの本棚ページに遷移する。

**Comment by tyokinuhata** [comment]
「読書メーター」、「Studyplus」などのサービスのトップページを参考に紙か何かにレイアウトを描いて共有してください。

その後、トップページのマークアップをざっとで良いのでお願いします。

**Comment by takashi0602** [comment]
重複しているため
